/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_maindialog (void);
GtkWidget* create_aboutdialog (void);
GtkWidget* create_propertiesdialog (void);
GtkWidget* create_newdialog (void);
GtkWidget* create_tundialog (void);
